version: "3"
services:
  app:
    container_name: search-microapi
    restart: always
    build: .
    ports:
      - "9207:9207"
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development